### ISSUE TITLE
Remember my choice on WAYF

### ISSUE THREAD

**Issue by mrvanes** [OpenConext/OpenConext-engineblock#278] opened 2016-03-11 08:00 UTC
Several potential OpenConext clients have expressed the wish to be able to skip the WAYF by letting users check a checkbox to "remember my choice".

**Comment by baszoetekouw** [comment] 2016-03-11 08:37
This would be a nice feature, but the user interaction consequences will have to be well thought trough.  For example, how would we facilitate users that click on the wrong IdP?

**Comment by mrvanes** [comment] 2016-03-11 08:37
The patch should fiscilitate a hard-coded cookie reset link

**Comment by surfnet-niels** [comment] 2016-03-11 08:40
Alternative could be "remember my choice for X time". That said, offering a zillion buttons and possibilities to end users will also not work well.

**Comment by baszoetekouw** [comment] 2016-03-11 08:44
Some ideas from the SKype discussion:
- auto-continue after a countdown of a few seconds
- make the browser back actually work (ie.: wrong IdP --> Back --> WAYF knows you're there for the second time (cookie magic) --> show WAYF and repick IdP)
- grub-like "hold control key during login to show WAYF"

**Comment by tvdijen** [comment] 2016-03-11 09:42
The back-button and hold-ctrl scenario's seem like the most user-friendly ones. Could even do both!

**Comment by mrvanes** [comment] 2016-03-11 09:50
Back-button could be problematic for IdP's that redirect on SSO endpoint. ADFS does this, IIRC.

**Comment by tvdijen** [comment] 2017-03-14 09:50
Any new ideas on this?
This has recently come up again amongst multiple clients and for one of them it's become a real deal-breaker..
How hard would it be to make OC remember a choice for the duration of the session (as a global configuration option)?

**Comment by baszoetekouw** [comment] 2017-03-14 10:34
@arnoutt What is your opinion on this feature request?

**Comment by thijskh** [comment] 2017-03-14 10:44
> How hard would it be to make OC remember a choice for the duration of the session

EB already does exactly this.

**Comment by arnoutt** [comment] 2017-03-14 10:51
I estimate this feature is not needed for SURFconext.

The hard part about this is, as discussed, how to allow user to undo their choice. The most user-friendly way would be to allow users to navigate to a separate interface (wayf.federation.tld or maybe even the profile page?) where they can reset their preference. However, this is probably also the most 'expensive' solution.

If users are more technically capable, the same could be achieved by (manually) removing a cookie. Keyboard option sounds nice, but most users won't understand this without proper documentation I think. And when they need to refer to documentation anyway, the cookie option might be just as good.

**Comment by baszoetekouw** [comment] 2017-03-22 08:15
@tvdijen could you please explain what the exact problem is for your customers?  Doesn't EB already behave as you expect (as @thijskh said)?

**Comment by tvdijen** [comment] 2017-03-22 12:53
EB does remember the last IdP but it doesn't auto-select it, only highlights/marks it. Both customers are currently used to this behaviour and migrating to a platform that doesn't have this feels like going back in time for them. Preferably, they only see the WAYF once per browser-session.

**Comment by thijskh** [comment] 2017-03-22 13:12
EB remembers the IdP for the duration of the EB session (which is not the browser session). So perhaps it's helpful to increase the EB session length?

**Comment by tvdijen** [comment] 2017-03-22 14:09
Thanks Thijs, could you point me in the right direction here? Where do I configure that?

**Comment by thijskh** [comment] 2017-03-22 14:26
The session length is directly based on PHP's session length, so you'd probably want to look in php.ini.

**Comment by tvdijen** [comment] 2017-03-23 11:01
Could it be that ForceAuthn=true forces the WAYF to show?

**Comment by tvdijen** [comment] 2017-03-23 13:31
I've tried setting `session.cookie_lifetime = 28800`, but it makes no difference at all...

**Comment by thijskh** [comment] 2017-03-23 15:58
Are the sessions indeed kept on this for this lifetime, or are they garbage collected by something else? E.g. a cron job?

**Comment by tvdijen** [comment] 2017-03-23 17:23
PHP settings are completely default here, so gc time-out is 1440 secs. It should at least survive my tests.

**Comment by tvdijen** [comment] 2017-03-27 10:20
Did some more testing..
- I go to SP A
- Select my org at the WAYF-screen
- Authenticate against IdP and get inside SP A
- Then I go to SP B
- WAYF-screen is printed again :(, EB SessionID is the same as during the first run.

Closing the browser at any point always leads to a new EB session, despite the `session.cookie_lifetime`.

**Comment by thijskh** [comment] 2017-03-30 15:21
Does SP B send `ForceAuthn`? If so, can you try with an SP without it?

**Comment by tvdijen** [comment] 2017-03-30 15:23
That's what I was thinking too, but I haven't been able to test it..
All SP's send `ForceAuthn`... I'll see if I can test it during the weekend.

**Comment by tvdijen** [comment] 2017-03-30 21:20
Okay, I've rebuilt the situation at home because I have a bit more possibilities there and I can provide logs here.
[saml_trace.txt](https://github.com/OpenConext/OpenConext-engineblock/files/883805/saml_trace.txt)

I've set up two Profile-SP's, both connected directly to one EB-instance, that in turn connects to an SSP IdP.
`session.cookie_lifetime` on the EB-instance is set to `28800`. I visit SP 1, then 2 and get the WAYF again, despite the fact I have the same session-id as you can see from the trace (`main=2phvrn8slltkijorp8n9226d81`).

Something I have noticed is this:
Mar 30 23:13:07 openconext-2 EBAUTH[18979]: 3 [TR065bd320] Error creating session: Headers already sent.
happening after authentication, returning from the IdP. No related context or whatsoever, even though I have set everything to DEBUG-logging...

I'm becoming a bit clueless here, so unless any of you have any suggestions left, would it be possible for me to drop by and going through the configuration together?

**Comment by DRvanR** [comment] 2017-03-31 07:02
So the actions are as follows:
you visit SP1 -> EB -> IdP -> EB -> SP1. Then you go to SP2, go to EB and then you expect EB to not show the wayf, right?

Which leads me to the question: how would EB know where you want to authenticate (which IdP to forward you to) for a different SP? E.g.: I want to log in at a SP from org A, select the corresponding IdP from org A on the WAYF and proceed with the authentication process. Then I want to log in at a different SP which belongs to org B, so at EB I'm presented with the choice of IdPs relevant for that SP. Now if that list also contains the IdP from org A, I still may not want to authenticate there, as it is for a different SP (hence the preselection, not the forwarding). 

EB has no knowledge whatsoever about organisations in this regard, but to me it seems that the expectation that a WAYF selection for SP1 to be used for an authentication for SP2 is something that is specific to your use-case, not something in a generic hub-spoke system. But I very well may be completely wrong here as to what you are trying to achieve :smile: (and frankly, I still do not know all configuration settings :wink: )

**Comment by thijskh** [comment] 2017-03-31 07:11
@DRvanR My impression is that the current algorithm that EB uses is, you select IdP A for SP 1, it remembers this in the session, and when you go to SP 2 and  SP 2 may log in to IdP A, it will automatically forward you to IdP A without wayf. When SP 2 does not allow IdP A, you will get the wayf.

**Comment by arnoutt** [comment] 2017-03-31 07:17
FWIW, a while ago SURFnet wrote a blog about SURFconext and sessions (only in Dutch): https://blog.surf.nl/sessieduur-bij-surfconext-een-afweging-tussen-gebruikersgemak-en-beveiliging/

**Comment by DRvanR** [comment] 2017-03-31 07:54
@thijskh you probably know better than me :wink: I've just been trying to follow the code, which supports your algorithm it seems... And come to think of it, that is the behavior I've been observing myself... hrms.

The session problem might be an issue, because if the session cannot be written, the IdP response is not cached and the automatic forwarding does not happen. Don't know how that can occur though, as we've never seen that before - also not in the automated tests..

**Comment by tvdijen** [comment] 2017-03-31 08:13
@DRvanR: That's indeed the scenario we're talking about.

From what the article describes: If the session on the SP ends **_or a new SP is opened_**, SURFconext will again display a WAYF for the user to select the appropriate institution.

Where can I find the code related to this decision? Perhaps I can 'help' it a bit to fit my use-case. If not, I think I have to resort to some actual custom coding.

**Comment by thijskh** [comment] 2017-03-31 08:25
I'm suspecting that ` Mar 30 23:13:07 openconext-2 EBAUTH[18979]: 3 [TR065bd320] Error creating session: Headers already sent.` is your problem. So you're not actually storing any sessions due to some problem in your installation. And this behaviour is just one symptom of it.

**Comment by tvdijen** [comment] 2017-03-31 08:59
Okay, let's not mix things up.. The `headers already sent` only shows in my home replica environment, not on the actual customer environment.

All SP's there are behind an SP-broker, so auth requests all come from one SP from EB's point of view.
The only thing I have to investigate is whether `ForceAuthn` is giving me a hard time now, but I don't control the SP-broker sending it ...

**Comment by thijskh** [comment] 2017-03-31 09:09
Alright, but those two things could lead to the same result. At home you're seeing it because sessions do not work, at the customer it does not work because everything is ForceAuthn?

**Comment by tvdijen** [comment] 2017-03-31 10:34
Aye, that's what it looks likes.
Any idea why session storage would fail? It doesn't matter whether I use phpsession or memcache.. SElinux is disabled..

**Comment by tvdijen** [comment] 2017-03-31 10:57
Okay, I've been able to fix the session problem.. It seems to be related to the version of SSP that's being used. Changed composer.json to:
        "simplesamlphp/saml2": "1.10.3 as 1.9.1",
         "simplesamlphp/simplesamlphp": "~1.14",

This is reproducable, so rolling back to the versions that originally come with the 5.2.3-release give me back the session creation errors.

Now when I go through the scenario, I only get to see the WAYF-screen once!

**Comment by mrvanes** [comment] 2017-03-31 11:02
The session creation failover because of headers sent most of the time is caused by code sending characters to stdout, if that occurs, PHP/Apache HAVE to send any headers set at THAT moment. Very often a closing end tag with whitespace causes this if the code is in "html" mode just before.
```
...

?>
```
Could it be you're sending unwanted/early output in debug code or own template?
Why a different php version would solve this I can't think of.

**Comment by thijskh** [comment] 2017-03-31 11:24
FWIW I don't have the problem with EB 5.2.3.

**Comment by tvdijen** [comment] 2017-03-31 11:47
Well, lots of session-related issues have been fixed in SSP since 1.13.2...
I guess it's an edge-case but it really fixes the problem for me in a reproducible way.

**Comment by tvdijen** [comment] 2017-03-31 12:15
Ok, I've been able to run tests with ForceAuthn now and that's indeed the culprit here.. Thanks again

**Comment by tvdijen** [comment] 2017-07-06 11:46
Okay, so for now this has been solved;  The SP's are not sending ForceAuthn anymore and I've set a lifetime on both the cookies (client-side) and the sessions (server-side) to stop them from being garbage-collected.

I do however have a concern for the long term..  My client basically doesn't want to see the WAYF more than once... EVER.. We've tried to convince them not to keep sessions forever, but ended up with a lifetime of one year anyway...  Now one month in production, we've already ended up with 25K sessions taking up 1,5 GB...

Shouldn't it be possible to auto-select the IdP based on a cookie, without having a session from a previous visit??

**Comment by tvdijen** [comment] 2017-07-19 11:48
Could really use some help here, because disks are exploding right now with tens of thousands php sessions... Would it be possible with some modification to the code to just auto-select the IdP based on the cookie, without saving sessions server-side?  I'm trying to find the code that's responsible for this process right now, but I can't find it... Help is appreciated!

**Comment by mrvanes** [comment] 2017-07-19 12:06
Hi Tim, not that I know exactly what the low-level details (code etc) are, but extending the lifetime of the WAYF cookie should reuse an existing session for the user and off-load the session store, is my guess? The question remains, where the WAYF cookie get's set. I don't think storing the IdP in a cookie would solve your problem, because the WAYF would still setup it's session regardless.

**Comment by tvdijen** [comment] 2017-07-19 12:23
That right, Martin.. Existing sessions... Which are becoming way to many if you have to save them for a year.

I'm looking for a solution similar to the one you've once made for our old NetIQ environment. If I can make the WAYF to auto-select an IdP based on a cookie, I can set the session lifetime back to 0..

**Comment by mrvanes** [comment] 2017-07-19 12:54
No. If my client would present a cookie associated with an existing and valid session PHP would only update the existing one (on disk) and not create a new one, unless the cookie or session I'm presenting is no long valid. So my hint is: make sure cookies and/or sessions live long enough to be reused, what sessions are meant for.

**Comment by tvdijen** [comment] 2017-07-19 13:10
I think we're out of sync here....

Remembering someone's choice is not the point here anymore.. It's working..  But the amount of session files is growing way out of control.. And it shouldn't be necessary to save them. Cookies don't need an associated session (except for a session-cookie).  Can you remember the custom JSP you've writen for NetIQ?

**Comment by thijskh** [comment] 2017-07-19 13:40
This is where the `selectedIdps` cookie is read.
https://github.com/OpenConext/OpenConext-engineblock/blob/master/theme/material/templates/modules/Authentication/View/Proxy/discover.phtml#L86-L123

There a list is constructed of the previously selected IdPs, and another list for the rest.

Maybe a quick fix would be to add some JS there that when there's >0 selected IdPs, that just submits the form (the top IdP will be selected already).

**Comment by tvdijen** [comment] 2017-07-19 14:55
Thanks Thijs! That's what I was looking for!

**Comment by thijskh** [comment] 2017-07-19 15:09
Note that you neef to 'compile' the theme when you make any changes there (see README).  What is actually used is the version under app/

**Comment by tvdijen** [comment] 2017-07-19 16:08
Yeah, I always need to edit that one, because I can't use the needed tools...

**Comment by tvdijen** [comment] 2017-07-25 16:00
Perhaps anyone wants to take a look at my code?
https://github.com/tvdijen/OpenConext-engineblock/commits/patch-autoselection

**Comment by MKodde** [comment] 2017-12-11 13:02
The feature was merged and is available behind a feature toggle. Who will update the documentation for this feature?

**Comment by tvdijen** [comment] 2017-12-11 13:20
Where should it go? On the wiki? In the /docs?

**Comment by MKodde** [comment] 2017-12-11 14:48
I would say Wiki, but I'm not entirely sure. @thijskh, where should this kind of features be documented?

**Comment by thijskh** [comment] 2017-12-18 14:50
I tend to say on the Wiki: https://github.com/OpenConext/OpenConext-engineblock/wiki

**Comment by thijskh** [comment] 2018-01-11 16:03
Fixed in EB 5.5

**Closed by thijskh** 2018-01-11 16:03 UTC
Labels: enhancement, wayf

**Comment by tvdijen** [comment] 2018-01-11 17:10
I still intent to write some documentation, but I couldn't really find a place on the Wiki to add this feature to..... Perhaps a new page describing all configuration settings?

**Comment by thijskh** [comment] 2018-01-11 18:51
It's currently quite under-documented, so indeed just start a page for that and we can add things as we go.
