### ISSUE TITLE
Issues encountered during update 6.1.3 > 6.3.5

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-engineblock#920] opened 2020-10-03 15:55 UTC
**1. Responses without NameID cause an error:**
```
  Oct  3 13:52:09 sv1810952 EBLOG[1527]: [2020-10-03 13:52:09] app.ERROR: Call to a member function getValue() on null {"session_id":"o6v872d3nh68rrlt1tn40jrv2g","request_id":"5f7865e9c3ebe"} {"exception":"[object] (Error(code: 0): Call to a member function getValue() on null at /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.3.5/library/EngineBlock/Corto/Filter/Abstract.php:75)"}
```
  It's likely related to the saml2-lib upgrade and [this PR](https://github.com/OpenConext/OpenConext-engineblock/pull/919) should probably fix that.. As per semver, this change should probably not have ended in a dot-release.. On the other hand, the changes in saml2 are not that significant..

**2. Metadata push failed with the following error:**
```
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'publish_in_edugain' doesn't have a default value in /apps/installation/OpenConext-engineblock/engine.example.org/OpenConext-engineblock-6.3.5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121
```

  Turns out that the migration to drop that column didn't make it any of the release branches or to `master`. I could easily fix this by marking it `DEFAULT NULL` in the schema, but it should be properly removed in a (bugfix-)release

**3. Metadata push causes errors (but I don't see immediate issues with the pushed metadata or EB workings):**
```
Oct  2 18:05:20 sv1910208 EBLOG-BZK[1416]: [2020-10-02 18:05:20] app.NOTICE: An error was caught {"session_id":"hdlfon3il15j3g3l16bi7lvj0l","request_id":"5f774fc05c6d1"} []
Oct  2 18:05:20 sv1910208 EBLOG-BZK[1416]: PHP Notice:  Trying to get property 'pt' of non-object in /apps/installation/OpenConext-engineblock/engine.example.org/OpenConext-engineblock-6.3.5/src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php on line 341
Oct  2 18:05:20 sv1910208 EBLOG-BZK[1416]: [2020-10-02 18:05:20] app.ERROR: Undefined property: stdClass::$OrganizationURL
/apps/installation/OpenConext-engineblock/engine.example.org/OpenConext-engineblock-6.3.5/src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php:342]
{"session_id":"hdlfon3il15j3g3l16bi7lvj0l","request_id":"5f774fc05c6d1"}{"exception":{"severity":"ERROR","location":"/apps/installation/OpenConext-engineblock/engine.example.org/OpenConext-engineblock-6.3.5/library/EngineBlock/Application/ErrorHandler.php:83","userId":null,"idp":null,"sp":null,"details":"EngineBlock_Exception: Undefined property: stdClass::$OrganizationURL
[/apps/installation/OpenConext-engineblock/engine.example.org/OpenConext-engineblock-6.3.5/src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php:342]
```

  I'm seeing these errors for all three languages, so not just 'pt'...
  Thijs mentioned there were no issues during tests, but all the instances I'm running (15+) show the same issue, so it's either an edge-case or I'm doing something consistently wrong..

**4. Database migration issue**
  I run several instances of OpenConext.. Some older than others.. On the older ones, database migration from 6.1.3 > 6.3.5 went fine, but the ones that were freshly installed with 6.1.3 earlier this year had the migration failing on `20191011132428`. The column being dropped, `response_processing_service_binding`, does not exist..  There must be something off between the migrations and the schema creation code.

**Comment by thijskh** [comment] 2020-10-03 18:32
1. The change seems not intentional. The saml2 upgrade is related to it because whete you earlier could get away with returning a null value, the saml2 lib requires you to call getValue() so the code in EB now needs an extra check that it didnt’t before.

2. Indeed the migration seems not to have been merged correctly.

3. I have checked but these messages do not appear in out logs. Must be related to some specific configuration.

**Comment by tvdijen** [comment] 2020-10-03 21:36
Regarding 1.  I guess EB checked the public property before instead of calling the getter-method, but didn't also had the possibility of returning null?
Regarding 3. I don't mind sharing our config, but it would help to have a pointer as to what possibly causes this..

**Comment by thijskh** [comment] 2020-10-04 09:07
I hope @MKodde can say something about where to look to reproduce this

**Comment by tvdijen** [comment] 2020-10-05 09:18
One more thing;
I've noticed a lot of these in the logs:  [2020-10-05 11:13:08] app.WARNING: No PT displayName and name found for idp

`WARNING` might be a bit much for a missing display name..

**Comment by thijskh** [comment] 2020-10-05 09:59
It is a problem as soon as you use such an entity (used in all the important screens) but should only be triggered when someone is using the PT interface I'd say.

**Comment by tvdijen** [comment] 2020-10-05 10:04
I only have 'en' and 'nl' enabled in the config

**Comment by MKodde** [comment] 2020-10-05 10:07
Regarding 2: there was a branch that was not yet merged during the 6.3 release. This branch was to be part of 6.3 and contained the migration that removes the remaining eduGAIN fields. I've opened #922 for this.

**Comment by tvdijen** [comment] 2020-10-05 10:08
Two down, two to go! 💪

**Comment by MKodde** [comment] 2020-10-05 11:53
Regarding 3: these notices and errors seem logical as the organization metadata is not required. So these errors should occur when trying to import them. And in my test setup they did occur. However when pushing the metadata from Manage, the logs do not show the notices. Could this be because the EB-API has different log preferences set up?

To prevent the errors, I've opened a PR that sharpens the import logic of the Organization data in the PushMetadataAssembler.

See: #923

**Comment by MKodde** [comment] 2020-10-05 12:55
Regarding 4: we had a discussion about the column we where dropping. Some environments had the column, others did not. This seemingly depends on when the schema was first created. As newer versions do not have the column in the database schema.

Best bet is to skip the migration. Alternatively we could try to first test if the column exists before dropping it. The `ALTER TABLE 'tablename' DROP 'foobar' IF EXISTS` can sadly not be used as that is not supported by MYSQL. 

See: https://github.com/OpenConext/OpenConext-engineblock/pull/782

**Comment by tvdijen** [comment] 2020-10-05 14:20
I think all it takes is to add these lines in the up-method:
```
        if (!$schema->getTable('sso_provider_roles_eb5')->hasColumn('response_processing_service_binding')) {
            $this->skipIf(true, 'Skipping this migration.');
        }
```

**Comment by MKodde** [comment] 2020-10-05 14:25
Yup just thought about that feature too! I'm updating my PR to use that feature. This could also be used for point 2. Might add that into the same PR while at it..

**Comment by MKodde** [comment] 2020-10-06 06:43
@tvdijen the four issues where resolved in release 6.3.6. I'm closing this ticket. Thanks for your help!

**Closed by MKodde** 2020-10-06 06:43 UTC
Labels: 6.3.6

**Comment by tvdijen** [comment] 2020-10-06 07:49
And thank you for solving the issues!! I'll try and give 6.3.6 a test-run later today

**Comment by tvdijen** [comment] 2020-10-06 11:02
OK, everything seems to be running fine now, except for the fact that I'm still spammed with:
Oct  6 12:58:27 sv1811043 EBLOG[31783]: [2020-10-06 12:58:27] app.WARNING: No PT displayName and name found for idp: http://sts.tstdwr.rijksweb.nl/adfs/services/trust {"session_id":"7045n4glv09o9d3ob5kajscu1h","request_id":"5f7c4dd3626b0"} {"additional_info":{"severity":null,"location":null,"userId":null,"idp":"http://sts.tstdwr.rijksweb.nl/adfs/services/trust","sp":null,"details":"","message_prefix":null}}

For each and every IDP, every time the WAYF is shown.. This cannot be a warning if the pt-language is not enabled..

**Comment by thijskh** [comment] 2020-10-06 14:55
Maybe for clarity we can make this a separate issue
